#Task 1

importing the requried libraries

In [21]:
import requests
import pandas as pd
import sqlite3

In [22]:
from google.colab import userdata
API_KEY = userdata.get('TMDB_API_KEY')

In [23]:
url = "https://api.themoviedb.org/3/discover/movie"

params={
    "api_key":API_KEY,
    "language":"en-US",
    "sort_by":"popularity.desc",
    "page":2
}
response = requests.get(url,params=params)
data = response.json()
movies = data['results']
df=pd.DataFrame(movies)
df = df[['id', 'title', 'release_date', 'vote_average', 'popularity', 'genre_ids']]
df.head()

,id,title,release_date,vote_average,popularity,genre_ids
0,1381216,Lake Jesup: Bonecrusher's Revenge,2024-05-01,6.219,94.9751,"[27, 35, 12]"
1,1572073,The Deadly Little Mermaid,2026-03-06,4.700,93.8508,[27]
2,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,2025-07-18,7.665,100.2238,"[16, 28, 14]"
3,467905,How to Make a Killing,2026-02-19,7.132,88.8231,"[35, 53]"
4,1236153,Mercy,2026-01-20,7.008,89.4526,"[878, 28, 53]"

In [24]:
conn = sqlite3.connect('movies.db')
df['genre_ids'] = df['genre_ids'].apply(str)
df.to_sql("movies",conn,if_exists="replace",index=False)
conn.close()

#Task 2

In [25]:
conn = sqlite3.connect('movies.db')
df= pd.read_sql("SELECT* FROM movies",conn)
df.head()

,id,title,release_date,vote_average,popularity,genre_ids
0,1381216,Lake Jesup: Bonecrusher's Revenge,2024-05-01,6.219,94.9751,"[27, 35, 12]"
1,1572073,The Deadly Little Mermaid,2026-03-06,4.700,93.8508,[27]
2,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,2025-07-18,7.665,100.2238,"[16, 28, 14]"
3,467905,How to Make a Killing,2026-02-19,7.132,88.8231,"[35, 53]"
4,1236153,Mercy,2026-01-20,7.008,89.4526,"[878, 28, 53]"

In [26]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            20 non-null     int64
 1   title         20 non-null     object
 2   release_date  20 non-null     object
 3   vote_average  20 non-null     float64
 4   popularity    20 non-null     float64
 5   genre_ids     20 non-null     object
dtypes: float64(2), int64(1), object(3)
memory usage: 1.1+ KB

                 id  vote_average  popularity
count  2.000000e+01     20.000000   20.000000
mean   1.164856e+06      6.562250   80.814465
std    3.741124e+05      1.125622   11.813604
min    4.679050e+05      4.149000   54.824200
25%    8.360288e+05      6.120250   69.599125
50%    1.235442e+06      6.952000   84.509250
75%    1.453528e+06      7.238000   88.783050
max    1.634301e+06      8.000000  100.223800

In [27]:
df_exploded= df.explode('genre_ids')
genre_counts = df_exploded['genre_ids'].value_counts()
genre_counts

genre_ids
[27, 35, 12]          1
[27]                  1
[16, 28, 14]          1
[35, 53]              1
[878, 28, 53]         1
[9648, 18, 27]        1
[28, 80, 53]          1
[28, 35, 80, 9648]    1
[878, 27]             1
[9648, 53]            1
[28, 53]              1
[878, 53]             1
[28, 12, 878]         1
[28]                  1
[28, 80, 18, 53]      1
[12, 35, 27]          1
[27, 18, 53]          1
[28, 18]              1
[53, 80, 18]          1
[12, 10752, 36]       1
Name: count, dtype: int64

In [28]:
df.isnull().sum()

id              0
title           0
release_date    0
vote_average    0
popularity      0
genre_ids       0
dtype: int64